In [2]:
import pandas as pd
import numpy as np

# Load the original dataset
df = pd.read_csv("../data/raw_dataset.csv")

# Display the first five rows
display(df.head())

,order_id,order_date,customer_id,customer_name,age,gender,region,city,product_category,product_name,...,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship
0,ORD-03903,2024-08-15,CUST32603,Aarav Mehta,39.0,Other,Central,Raipur,Groceries,Sugar,...,346.32,NaN,4043.14,289.18,56.04,Debit Card,NaN,True,Returned,7.0
1,ORD-02198,2022-08-16,CUST07881,Sanjay Verma,28.0,Male,West,Mumbai,Beauty,Sunscreen,...,858.66,0.08,9147.31,5355.56,64.49,Debit Card,5.0,False,Delivered,2.0
2,ORD-01348,2021-08-29,CUST49296,Pooja Sharma,41.0,Other,West,Surat,Furniture,Sofa,...,25941.32,0.14,110156.97,36956.51,67.65,Debit Card,4.0,False,Delivered,5.0
3,ORD-02076,2022-07-05,CUST05587,Priya Reddy,29.0,Other,West,Ahmedabad,Furniture,Bed Frame,...,22071.92,0.17,262066.11,66644.99,54.47,EMI,3.0,False,Delivered,4.0
4,ORD-00287,2020-05-07,CUST58035,Ritu Sharma,9.0,Male,Central,Nagpur,Groceries,Cooking Oil,...,320.06,0.31,323.95,31.38,48.81,Net Banking,4.0,False,Pending,4.0

In [3]:
# Number of rows and columns
print("Dataset shape:", df.shape)

# Column names
print("\nColumn names:")
print(df.columns.tolist())

# Data types and non-null counts
print("\nDataset information:")
df.info()

# Missing values in each column
print("\nMissing values:")
print(df.isnull().sum())

# Duplicate rows
print("\nDuplicate rows:", df.duplicated().sum())

Dataset shape: (4310, 21)

Column names:
['order_id', 'order_date', 'customer_id', 'customer_name', 'age', 'gender', 'region', 'city', 'product_category', 'product_name', 'quantity', 'unit_price', 'discount_pct', 'sales_amount', 'profit', 'shipping_cost', 'payment_method', 'customer_satisfaction', 'return_flag', 'order_status', 'days_to_ship']

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 4310 entries, 0 to 4309
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               4280 non-null   str
 1   order_date             4280 non-null   str
 2   customer_id            4280 non-null   str
 3   customer_name          4280 non-null   str
 4   age                    4150 non-null   float64
 5   gender                 4280 non-null   str
 6   region                 4280 non-null   str
 7   city                   4280 non-null   str
 8   product_category       4280 non-null   str
 9   product_name           4280 non-null   str
 10  quantity               4170 non-null   float64
 11  unit_price             4280 non-null   float64
 12  discount_pct           4143 non-null   float64
 13  sales_amount           4280 non-null   float64
 14  profit                 4280 non-null   float64
 15  shipping_cost          4280 non-null   float64
 16  payment_method         4280 non-null   str
 17  customer_satisfaction  3932 non-null   float64
 18  return_flag            4280 non-null   object
 19  order_status           4280 non-null   str
 20  days_to_ship           4180 non-null   float64
dtypes: float64(9), object(1), str(11)
memory usage: 707.2+ KB

Missing values:
order_id                  30
order_date                30
customer_id               30
customer_name             30
age                      160
gender                    30
region                    30
city                      30
product_category          30
product_name              30
quantity                 140
unit_price                30
discount_pct             167
sales_amount              30
profit                    30
shipping_cost             30
payment_method            30
customer_satisfaction    378
return_flag               30
order_status              30
days_to_ship             130
dtype: int64

Duplicate rows: 109

In [4]:
df.shape

df.isnull().sum()

df.duplicated().sum()

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4310 entries, 0 to 4309
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               4280 non-null   str
 1   order_date             4280 non-null   str
 2   customer_id            4280 non-null   str
 3   customer_name          4280 non-null   str
 4   age                    4150 non-null   float64
 5   gender                 4280 non-null   str
 6   region                 4280 non-null   str
 7   city                   4280 non-null   str
 8   product_category       4280 non-null   str
 9   product_name           4280 non-null   str
 10  quantity               4170 non-null   float64
 11  unit_price             4280 non-null   float64
 12  discount_pct           4143 non-null   float64
 13  sales_amount           4280 non-null   float64
 14  profit                 4280 non-null   float64
 15  shipping_cost          4280 non-null   float64
 16  payment_method         4280 non-null   str
 17  customer_satisfaction  3932 non-null   float64
 18  return_flag            4280 non-null   object
 19  order_status           4280 non-null   str
 20  days_to_ship           4180 non-null   float64
dtypes: float64(9), object(1), str(11)
memory usage: 707.2+ KB

In [5]:
# Count completely empty rows
empty_rows = df.isnull().all(axis=1).sum()

print("Completely empty rows:", empty_rows)

# Count fully duplicated rows
duplicate_rows = df.duplicated().sum()

print("Fully duplicated rows:", duplicate_rows)

# Inspect rows with missing order IDs
print("\nRows with missing order IDs:")
display(df[df["order_id"].isnull()].head(10))

Completely empty rows: 30
Fully duplicated rows: 109

Rows with missing order IDs:

,order_id,order_date,customer_id,customer_name,age,gender,region,city,product_category,product_name,...,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Store the original number of rows
original_rows = len(df)

# Remove completely empty rows
df = df.dropna(how="all")

# Count rows after removing empty rows
rows_after_empty_removal = len(df)

# Remove exact duplicate records
df = df.drop_duplicates()

# Count rows after removing duplicates
cleaned_rows = len(df)

# Display the results
print("Original rows:", original_rows)
print("Completely empty rows removed:",
      original_rows - rows_after_empty_removal)
print("Duplicate rows removed:",
      rows_after_empty_removal - cleaned_rows)
print("Rows remaining:", cleaned_rows)

Original rows: 4310
Completely empty rows removed: 30
Duplicate rows removed: 80
Rows remaining: 4200

In [7]:

# Inspect categorical columns for inconsistent values

categorical_columns = [
    "gender",
    "region",
    "city",
    "product_category",
    "product_name",
    "payment_method",
    "order_status",
    "return_flag"
]

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(25))

--- gender ---
gender
Other     1419
Male      1178
Female    1172
male        67
MALE        61
f           55
F           53
m           53
M           49
FEMALE      48
female      45
Name: count, dtype: int64

--- region ---
region
West       869
South      866
North      848
East       833
Central    784
Name: count, dtype: int64

--- city ---
city
Amritsar       236
Surat          232
Guwahati       232
Chennai        231
Mumbai         226
Raipur         220
Hyderabad      220
Chandigarh     214
Kolkata        213
Ahmedabad      211
Bangalore      209
Kochi          206
Nagpur         204
Ludhiana       201
Pune           200
Patna          197
Delhi          197
Bhubaneswar    191
Indore         185
Bhopal         175
Name: count, dtype: int64

--- product_category ---
product_category
Clothing       632
Sports         614
Electronics    608
Groceries      607
Beauty         601
Furniture      576
Books          562
Name: count, dtype: int64

--- product_name ---
product_name
Dal (1kg)         115
Headphones        115
Jeans             115
Shampoo           115
Face Cream        113
Sunscreen         112
Tennis Racket     112
Fiction Novel     112
Textbook          112
Dress             110
Laptop            109
Desk              109
Saree             108
Kurta             107
Dumbbells         107
Bed Frame         105
Cricket Bat       105
Football          104
Rice (5kg)        104
Cooking Oil       103
Hair Oil          102
Smartwatch        102
Yoga Mat          101
Tea                98
Self-Help Book     97
Name: count, dtype: int64

--- payment_method ---
payment_method
UPI                 749
Credit Card         721
Cash on Delivery    703
Debit Card          683
EMI                 683
Net Banking         661
Name: count, dtype: int64

--- order_status ---
order_status
Delivered    2613
Returned      612
Cancelled     333
Shipped       312
Pending       178
delivered     118
shipped        15
cancelled      13
pending         6
Name: count, dtype: int64

--- return_flag ---
return_flag
False    3588
True      612
Name: count, dtype: int64

In [8]:

# Remove leading/trailing spaces from text columns
for col in categorical_columns:
    df[col] = df[col].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

# Standardize gender values
gender_mapping = {
    "male": "Male",
    "m": "Male",
    "female": "Female",
    "f": "Female",
    "other": "Other"
}

df["gender"] = df["gender"].apply(
    lambda x: gender_mapping.get(x.lower(), x)
    if isinstance(x, str) else x
)

# Check the cleaned gender values
print(df["gender"].value_counts(dropna=False))

gender
Other     1419
Male      1408
Female    1373
Name: count, dtype: int64

In [9]:

# Inspect different date formats
print("Sample dates:")
print(df["order_date"].head(15).to_list())

print("\nData type before cleaning:")
print(df["order_date"].dtype)

print("\nMissing dates:")
print(df["order_date"].isna().sum())

print("\nExample distinct dates:")
print(df["order_date"].dropna().drop_duplicates().head(15).to_list())

Sample dates:
['2024-08-15', '2022-08-16', '2021-08-29', '2022-07-05', '2020-05-07', '02/09/2024', '2021-09-28', '2023-06-10', '2020-07-24', '2020-02-09', '2020-06-04', '2022-01-28', '2022-09-14', '2024-01-21', '2023-01-04']

Data type before cleaning:
str

Missing dates:
0

Example distinct dates:
['2024-08-15', '2022-08-16', '2021-08-29', '2022-07-05', '2020-05-07', '02/09/2024', '2021-09-28', '2023-06-10', '2020-07-24', '2020-02-09', '2020-06-04', '2022-01-28', '2022-09-14', '2024-01-21', '2023-01-04']

In [10]:

# Remove any accidental spaces
date_text = df["order_date"].astype("string").str.strip()

# Identify dates in YYYY-MM-DD format
iso_format = date_text.str.match(
    r"^\d{4}-\d{2}-\d{2}$", na=False
)

# Create a datetime column
clean_dates = pd.Series(
    pd.NaT, index=df.index, dtype="datetime64[ns]"
)

# Parse YYYY-MM-DD dates
clean_dates.loc[iso_format] = pd.to_datetime(
    date_text.loc[iso_format],
    format="%Y-%m-%d",
    errors="coerce"
)

# Parse DD/MM/YYYY dates
clean_dates.loc[~iso_format] = pd.to_datetime(
    date_text.loc[~iso_format],
    format="%d/%m/%Y",
    errors="coerce"
)

# Update the dataset
df["order_date"] = clean_dates

# Verify the conversion
print("Data type after cleaning:", df["order_date"].dtype)
print("Missing dates after conversion:", df["order_date"].isna().sum())
print("\nSample cleaned dates:")
print(df["order_date"].head(15))

Data type after cleaning: datetime64[ns]
Missing dates after conversion: 120

Sample cleaned dates:
0    2024-08-15
1    2022-08-16
2    2021-08-29
3    2022-07-05
4    2020-05-07
5    2024-09-02
6    2021-09-28
7    2023-06-10
8    2020-07-24
9    2020-02-09
10   2020-06-04
11   2022-01-28
12   2022-09-14
13   2024-01-21
14   2023-01-04
Name: order_date, dtype: datetime64[ns]

In [11]:

# Reload only the original date column
raw_dates = pd.read_csv(
    "../data/raw_dataset.csv",
    usecols=["order_date"]
)["order_date"].astype("string").str.strip()

# Identify the two expected formats
iso_format = raw_dates.str.match(
    r"^\d{4}-\d{2}-\d{2}$", na=False
)

dmy_format = raw_dates.str.match(
    r"^\d{2}/\d{2}/\d{4}$", na=False
)

# Display format counts
print("YYYY-MM-DD format:", iso_format.sum())
print("DD/MM/YYYY format:", dmy_format.sum())
print("Missing or unexpected formats:",
      (~(iso_format | dmy_format)).sum())

# Show unexpected values
unexpected_dates = raw_dates[~(iso_format | dmy_format)]

print("\nUnexpected date values:")
print(unexpected_dates.value_counts(dropna=False).head(30))

YYYY-MM-DD format: 4007
DD/MM/YYYY format: 150
Missing or unexpected formats: 153

Unexpected date values:
order_date
<NA>                  30
February 27, 2023      2
January 01, 2023       2
April 24, 2022         2
August 15, 2022        2
August 17, 2024        1
November 22, 2024      1
April 08, 2020         1
November 30, 2020      1
February 05, 2024      1
June 15, 2024          1
June 19, 2024          1
July 10, 2020          1
July 12, 2021          1
May 30, 2022           1
August 05, 2022        1
February 20, 2020      1
May 01, 2022           1
August 03, 2022        1
August 16, 2024        1
April 27, 2021         1
May 20, 2023           1
August 05, 2023        1
September 04, 2024     1
November 23, 2021      1
April 17, 2021         1
November 15, 2022      1
June 24, 2024          1
October 22, 2020       1
February 06, 2020      1
Name: count, dtype: Int64

In [12]:

# Create an empty datetime series
clean_dates = pd.Series(
    pd.NaT, index=raw_dates.index, dtype="datetime64[ns]"
)

# Format 1: YYYY-MM-DD
iso_format = raw_dates.str.match(
    r"^\d{4}-\d{2}-\d{2}$", na=False
)
clean_dates.loc[iso_format] = pd.to_datetime(
    raw_dates.loc[iso_format],
    format="%Y-%m-%d",
    errors="coerce"
)

# Format 2: DD/MM/YYYY
dmy_format = raw_dates.str.match(
    r"^\d{2}/\d{2}/\d{4}$", na=False
)
clean_dates.loc[dmy_format] = pd.to_datetime(
    raw_dates.loc[dmy_format],
    format="%d/%m/%Y",
    errors="coerce"
)

# Format 3: Month DD, YYYY
written_format = ~(iso_format | dmy_format) & raw_dates.notna()
clean_dates.loc[written_format] = pd.to_datetime(
    raw_dates.loc[written_format],
    format="%B %d, %Y",
    errors="coerce"
)

# Update the cleaned dataset
df["order_date"] = clean_dates

# Verify results
print("Original missing dates:", raw_dates.isna().sum())
print("Missing dates after cleaning:", df["order_date"].isna().sum())
print("Valid dates:", df["order_date"].notna().sum())
print("Final date data type:", df["order_date"].dtype)

# Check whether any non-missing source dates failed to parse
failed_dates = raw_dates.notna() & df["order_date"].isna()
print("\nNon-missing dates that failed to parse:", failed_dates.sum())
print(raw_dates[failed_dates].value_counts().head(20))

Original missing dates: 30
Missing dates after cleaning: 0
Valid dates: 4200
Final date data type: datetime64[ns]

Non-missing dates that failed to parse: 0
Series([], Name: count, dtype: Int64)

In [13]:

print("Current dataset rows:", len(df))
print("Current missing dates:", df["order_date"].isna().sum())

# Compare the original row indices still present in df
print("Current index range:", df.index.min(), "to", df.index.max())
print("Missing dates in original source:", raw_dates.isna().sum())

Current dataset rows: 4200
Current missing dates: 0
Current index range: 0 to 4309
Missing dates in original source: 30

In [14]:

# Inspect age statistics
print("Age data type:", df["age"].dtype)
print("Missing ages:", df["age"].isna().sum())

print("\nAge statistics:")
print(df["age"].describe())

print("\nLowest ages:")
print(df["age"].value_counts().sort_index().head(20))

print("\nHighest ages:")
print(df["age"].value_counts().sort_index().tail(20))

print("\nAges below 18:")
print((df["age"] < 18).sum())

print("\nAges above 100:")
print((df["age"] > 100).sum())

Age data type: float64
Missing ages: 125

Age statistics:
count    4075.000000
mean       35.371534
std        35.997612
min        -7.000000
25%        26.000000
50%        34.000000
75%        42.000000
max       999.000000
Name: age, dtype: float64

Lowest ages:
age
-7.0      2
-6.0      1
-5.0      4
-4.0      2
-2.0      2
-1.0      1
 0.0      5
 1.0      2
 2.0      3
 3.0      9
 4.0      5
 5.0      8
 6.0     11
 7.0     10
 8.0     12
 9.0     11
 10.0    12
 11.0    18
 12.0    28
 13.0    21
Name: count, dtype: int64

Highest ages:
age
54.0     35
55.0     29
56.0     24
57.0     24
58.0     27
59.0     14
60.0     15
61.0     11
62.0      6
63.0      8
64.0      4
65.0      5
66.0      6
67.0      3
68.0      3
69.0      1
71.0      2
72.0      1
150.0     3
999.0     5
Name: count, dtype: int64

Ages below 18:
329

Ages above 100:
8

In [15]:

# Count invalid ages before cleaning
invalid_age_mask = (df["age"] < 18) | (df["age"] > 100)

print("Invalid ages before cleaning:", invalid_age_mask.sum())
print("\nExamples of invalid ages:")
print(df.loc[invalid_age_mask, "age"].value_counts().sort_index())

# Replace invalid ages with missing values
df.loc[invalid_age_mask, "age"] = np.nan

# Calculate median using valid ages only
median_age = df["age"].median()

print("\nMedian age of valid records:", median_age)
print("Missing ages after validation:", df["age"].isna().sum())

Invalid ages before cleaning: 337

Examples of invalid ages:
age
-7.0       2
-6.0       1
-5.0       4
-4.0       2
-2.0       2
-1.0       1
 0.0       5
 1.0       2
 2.0       3
 3.0       9
 4.0       5
 5.0       8
 6.0      11
 7.0      10
 8.0      12
 9.0      11
 10.0     12
 11.0     18
 12.0     28
 13.0     21
 14.0     42
 15.0     47
 16.0     38
 17.0     35
 150.0     3
 999.0     5
Name: count, dtype: int64

Median age of valid records: 35.0
Missing ages after validation: 462

In [16]:
# Fill missing ages using the median
df["age"] = df["age"].fillna(median_age)

# Verify the result
print("Missing ages after imputation:", df["age"].isna().sum())
print("Median used for imputation:", median_age)
print("\nUpdated age statistics:")
print(df["age"].describe())

Missing ages after imputation: 0
Median used for imputation: 35.0

Updated age statistics:
count    4200.000000
mean       35.968571
std         9.754816
min        18.000000
25%        29.000000
50%        35.000000
75%        42.000000
max        72.000000
Name: age, dtype: float64

In [17]:
# Inspect quantity column
print("Data type:", df["quantity"].dtype)
print("Missing quantities:", df["quantity"].isna().sum())

print("\nQuantity statistics:")
print(df["quantity"].describe())

print("\nQuantity values in ascending order:")
print(df["quantity"].value_counts().sort_index().head(20))

print("\nZero or negative quantities:")
print((df["quantity"] <= 0).sum())

Data type: float64
Missing quantities: 108

Quantity statistics:
count    4092.000000
mean        7.419110
std        43.988899
min        -1.000000
25%         3.000000
50%         5.000000
75%         8.000000
max       999.000000
Name: quantity, dtype: float64

Quantity values in ascending order:
quantity
-1.0        6
 0.0       12
 1.0      407
 2.0      426
 3.0      417
 4.0      420
 5.0      372
 6.0      359
 7.0      395
 8.0      432
 9.0      432
 10.0     406
 999.0      8
Name: count, dtype: int64

Zero or negative quantities:
18

In [18]:
# Count suspicious quantities before cleaning
print("Negative or zero quantities:", (df["quantity"] <= 0).sum())
print("Quantities equal to 999:", (df["quantity"] == 999).sum())

# Replace invalid quantities with missing values
invalid_quantity = (df["quantity"] <= 0) | (df["quantity"] == 999)
df.loc[invalid_quantity, "quantity"] = np.nan

# Calculate median from valid quantities
median_quantity = df["quantity"].median()

print("\nMedian valid quantity:", median_quantity)
print("Missing quantities after validation:", df["quantity"].isna().sum())

Negative or zero quantities: 18
Quantities equal to 999: 8

Median valid quantity: 5.0
Missing quantities after validation: 134

In [19]:
# Fill missing quantities using the median
df["quantity"] = df["quantity"].fillna(median_quantity)

# Verify the result
print("Missing quantities after imputation:", df["quantity"].isna().sum())
print("Median used:", median_quantity)

print("\nUpdated quantity statistics:")
print(df["quantity"].describe())

print("\nUnique quantity values:")
print(sorted(df["quantity"].unique()))

Missing quantities after imputation: 0
Median used: 5.0

Updated quantity statistics:
count    4200.000000
mean        5.486429
std         2.859296
min         1.000000
25%         3.000000
50%         5.000000
75%         8.000000
max        10.000000
Name: quantity, dtype: float64

Unique quantity values:
[np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0), np.float64(10.0)]

In [20]:
# Inspect discount_pct
print("Data type:", df["discount_pct"].dtype)
print("Missing discounts:", df["discount_pct"].isna().sum())

print("\nDiscount statistics:")
print(df["discount_pct"].describe())

print("\nLowest discount values:")
print(df["discount_pct"].value_counts().sort_index().head(15))

print("\nDiscounts below 0:", (df["discount_pct"] < 0).sum())
print("Discounts above 100:", (df["discount_pct"] > 100).sum())

Data type: float64
Missing discounts: 135

Discount statistics:
count    4065.000000
mean        0.201877
std         0.118030
min         0.000000
25%         0.100000
50%         0.210000
75%         0.310000
max         0.400000
Name: discount_pct, dtype: float64

Lowest discount values:
discount_pct
0.00     44
0.01    109
0.02    107
0.03    112
0.04    120
0.05    107
0.06    111
0.07    102
0.08     82
0.09    104
0.10     77
0.11    105
0.12    105
0.13    103
0.14     94
Name: count, dtype: int64

Discounts below 0: 0
Discounts above 100: 0

In [21]:
# Calculate the median from existing valid discounts
median_discount = df["discount_pct"].median()

print("Median discount:", median_discount)

# Fill missing discounts using the median
df["discount_pct"] = df["discount_pct"].fillna(median_discount)

# Verify the result
print("Missing discounts after imputation:", df["discount_pct"].isna().sum())
print("\nUpdated discount statistics:")
print(df["discount_pct"].describe())

Median discount: 0.21
Missing discounts after imputation: 0

Updated discount statistics:
count    4200.000000
mean        0.202138
std         0.116126
min         0.000000
25%         0.100000
50%         0.210000
75%         0.300000
max         0.400000
Name: discount_pct, dtype: float64

In [22]:
# Inspect customer satisfaction
print("Data type:", df["customer_satisfaction"].dtype)
print("Missing ratings:", df["customer_satisfaction"].isna().sum())

print("\nRating statistics:")
print(df["customer_satisfaction"].describe())

print("\nRating value counts:")
print(df["customer_satisfaction"].value_counts().sort_index())

print("\nRatings below 1:", (df["customer_satisfaction"] < 1).sum())
print("Ratings above 5:", (df["customer_satisfaction"] > 5).sum())

Data type: float64
Missing ratings: 346

Rating statistics:
count    3854.000000
mean        3.017903
std         1.414008
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: customer_satisfaction, dtype: float64

Rating value counts:
customer_satisfaction
1.0    761
2.0    763
3.0    748
4.0    810
5.0    772
Name: count, dtype: int64

Ratings below 1: 0
Ratings above 5: 0

In [23]:
# Keep missing ratings as missing; verify the valid range
valid_ratings = df["customer_satisfaction"].dropna()

print("Missing ratings retained:", df["customer_satisfaction"].isna().sum())
print("All observed ratings between 1 and 5:",
      valid_ratings.between(1, 5).all())
print("Number of valid ratings:", valid_ratings.count())

Missing ratings retained: 346
All observed ratings between 1 and 5: True
Number of valid ratings: 3854

In [24]:
# Inspect shipping time
print("Data type:", df["days_to_ship"].dtype)
print("Missing shipping times:", df["days_to_ship"].isna().sum())

print("\nShipping-time statistics:")
print(df["days_to_ship"].describe())

print("\nShipping-time value counts:")
print(df["days_to_ship"].value_counts().sort_index())

print("\nZero or negative shipping times:",
      (df["days_to_ship"] <= 0).sum())

print("\nShipping time by order status:")
print(
    df.groupby("order_status", dropna=False)["days_to_ship"]
      .agg(["count", "mean", "min", "max"])
)

Data type: float64
Missing shipping times: 97

Shipping-time statistics:
count    4103.000000
mean        5.622715
std         4.196884
min        -1.000000
25%         3.000000
50%         6.000000
75%         8.000000
max       100.000000
Name: days_to_ship, dtype: float64

Shipping-time value counts:
days_to_ship
-1.0        5
 0.0        2
 1.0      377
 2.0      413
 3.0      433
 4.0      407
 5.0      400
 6.0      413
 7.0      397
 8.0      446
 9.0      410
 10.0     394
 45.0       2
 100.0      4
Name: count, dtype: int64

Zero or negative shipping times: 7

Shipping time by order status:
              count      mean  min    max
order_status
Cancelled       329  5.392097  1.0   10.0
Delivered      2552  5.679859 -1.0  100.0
Pending         172  5.389535  0.0   10.0
Returned        600  5.643333 -1.0   10.0
Shipped         300  5.333333 -1.0   10.0
cancelled        13  5.384615  1.0   10.0
delivered       116  6.008621  1.0   10.0
pending           6  3.666667  1.0    7.0
shipped          15  6.600000  1.0   10.0

In [25]:
# Count unusual shipping times
print("Negative shipping times:", (df["days_to_ship"] < 0).sum())
print("Zero shipping times:", (df["days_to_ship"] == 0).sum())
print("Shipping times above 30 days:", (df["days_to_ship"] > 30).sum())

# Display records with unusually high shipping times
print("\nRecords with shipping times above 30 days:")
print(
    df.loc[
        df["days_to_ship"] > 30,
        ["order_id", "order_status", "days_to_ship"]
    ]
)

Negative shipping times: 5
Zero shipping times: 2
Shipping times above 30 days: 6

Records with shipping times above 30 days:
       order_id order_status  days_to_ship
57    ORD-00357    Delivered          45.0
929   ORD-03303    Delivered         100.0
2226  ORD-01210    Delivered         100.0
2803  ORD-01340    Delivered         100.0
2866  ORD-01918    Delivered          45.0
3504  ORD-00470    Delivered         100.0

In [26]:
# Standardize order status capitalization
df["order_status"] = df["order_status"].apply(
    lambda x: x.strip().capitalize()
    if isinstance(x, str) else x
)

# Count shipping times outside the chosen plausible range
invalid_shipping = (
    (df["days_to_ship"] < 1) |
    (df["days_to_ship"] > 30)
)

print("Invalid shipping times:", invalid_shipping.sum())

# Replace invalid shipping times with missing values
df.loc[invalid_shipping, "days_to_ship"] = np.nan

# Check results
print("Missing shipping times after validation:",
      df["days_to_ship"].isna().sum())

print("\nStandardized order statuses:")
print(df["order_status"].value_counts(dropna=False))

print("\nShipping-time statistics after validation:")
print(df["days_to_ship"].describe())

Invalid shipping times: 13
Missing shipping times after validation: 110

Standardized order statuses:
order_status
Delivered    2731
Returned      612
Cancelled     346
Shipped       327
Pending       184
Name: count, dtype: int64

Shipping-time statistics after validation:
count    4090.000000
mean        5.522005
std         2.849383
min         1.000000
25%         3.000000
50%         6.000000
75%         8.000000
max        10.000000
Name: days_to_ship, dtype: float64

In [27]:
# Examine missing shipping times by order status
print("Missing shipping times by order status:")
print(
    df.groupby("order_status")["days_to_ship"]
      .agg(
          total_orders="size",
          missing_shipping_times=lambda x: x.isna().sum()
      )
)

print("\nMissing shipping time records:")
print(
    df.loc[
        df["days_to_ship"].isna(),
        ["order_id", "order_status", "days_to_ship"]
    ]["order_status"].value_counts()
)

Missing shipping times by order status:
              total_orders  missing_shipping_times
order_status
Cancelled              346                       4
Delivered             2731                      72
Pending                184                       7
Returned               612                      14
Shipped                327                      13

Missing shipping time records:
order_status
Delivered    72
Returned     14
Shipped      13
Pending       7
Cancelled     4
Name: count, dtype: int64

In [28]:
# Keep unknown shipping times as missing
print("Total orders:", len(df))
print("Missing shipping times retained:", df["days_to_ship"].isna().sum())
print("Valid shipping times:", df["days_to_ship"].notna().sum())

# Confirm remaining shipping times are within the selected range
valid_shipping = df["days_to_ship"].dropna()

print(
    "All valid shipping times between 1 and 30 days:",
    valid_shipping.between(1, 30).all()
)

Total orders: 4200
Missing shipping times retained: 110
Valid shipping times: 4090
All valid shipping times between 1 and 30 days: True

In [29]:
financial_columns = [
    "unit_price",
    "sales_amount",
    "profit",
    "shipping_cost"
]

print("Missing values:")
print(df[financial_columns].isna().sum())

print("\nFinancial statistics:")
print(df[financial_columns].describe())

print("\nNumber of negative values:")
print((df[financial_columns] < 0).sum())

print("\nNumber of zero values:")
print((df[financial_columns] == 0).sum())

Missing values:
unit_price       0
sales_amount     0
profit           0
shipping_cost    0
dtype: int64

Financial statistics:
         unit_price  sales_amount        profit  shipping_cost
count   4200.000000  4.200000e+03  4.200000e+03    4200.000000
mean   10702.729695  6.292138e+04  1.179028e+04      63.378790
std    17408.776463  3.195126e+05  5.335219e+04      18.317527
min       50.260000  3.945000e+01  1.560000e+00      -4.290000
25%      680.817500  2.472295e+03  7.120700e+02      50.827500
50%     2246.005000  9.647895e+03  3.169875e+03      63.460000
75%    12828.977500  5.052485e+04  1.051096e+04      75.655000
max    79957.920000  1.736031e+07  2.445648e+06     133.350000

Number of negative values:
unit_price       0
sales_amount     0
profit           0
shipping_cost    2
dtype: int64

Number of zero values:
unit_price       0
sales_amount     0
profit           0
shipping_cost    0
dtype: int64

In [30]:
# Inspect negative shipping costs
print("Records with negative shipping costs:")
print(
    df.loc[
        df["shipping_cost"] < 0,
        ["order_id", "quantity", "unit_price",
         "discount_pct", "sales_amount", "profit", "shipping_cost"]
    ]
)

# Inspect the five largest sales amounts
print("\nFive largest sales amounts:")
print(
    df.nlargest(5, "sales_amount")[
        ["order_id", "quantity", "unit_price",
         "discount_pct", "sales_amount", "profit", "shipping_cost"]
    ]
)

Records with negative shipping costs:
       order_id  quantity  unit_price  discount_pct  sales_amount    profit  \
1878  ORD-03203       5.0    30014.40          0.11     131495.05  42093.32
2012  ORD-00576      10.0     2950.98          0.23      23921.04   3847.48

      shipping_cost
1878          -3.11
2012          -4.29

Five largest sales amounts:
       order_id  quantity  unit_price  discount_pct  sales_amount      profit  \
3865  ORD-02560       5.0    18619.45          0.00   17360314.17  2445648.43
1138  ORD-01025       5.0     9380.72          0.29    7936261.20  1739854.00
2582  ORD-00809       5.0     3280.13          0.03    2586345.13   921794.60
1112  ORD-00539       5.0     2567.40          0.31    2281458.22   899209.60
2379  ORD-03003      10.0    76450.07          0.02    1182709.24   198109.98

      shipping_cost
3865          82.19
1138          72.62
2582          83.69
1112          74.46
2379          72.05

In [31]:
# Calculate expected sales using quantity, unit price, and discount
df["expected_sales"] = (
    df["quantity"]
    * df["unit_price"]
    * (1 - df["discount_pct"])
)

# Compare expected and recorded sales
df["sales_difference"] = (
    df["sales_amount"] - df["expected_sales"]
)

print("Five largest recorded sales amounts:")
print(
    df.nlargest(5, "sales_amount")[
        ["order_id", "quantity", "unit_price", "discount_pct",
         "expected_sales", "sales_amount", "sales_difference"]
    ].round(2)
)

print("\nRecords where recorded sales differ from expected sales by over 10%:")
difference_pct = (
    df["sales_difference"].abs()
    / df["expected_sales"].abs()
)
print((difference_pct > 0.10).sum())

Five largest recorded sales amounts:
       order_id  quantity  unit_price  discount_pct  expected_sales  \
3865  ORD-02560       5.0    18619.45          0.00        93097.25
1138  ORD-01025       5.0     9380.72          0.29        33301.56
2582  ORD-00809       5.0     3280.13          0.03        15908.63
1112  ORD-00539       5.0     2567.40          0.31         8857.53
2379  ORD-03003      10.0    76450.07          0.02       749210.69

      sales_amount  sales_difference
3865   17360314.17       17267216.92
1138    7936261.20        7902959.64
2582    2586345.13        2570436.50
1112    2281458.22        2272600.69
2379    1182709.24         433498.55

Records where recorded sales differ from expected sales by over 10%:
3277

In [32]:
# Count negative shipping costs before cleaning
negative_shipping_costs = (df["shipping_cost"] < 0).sum()

print("Negative shipping costs before cleaning:",
      negative_shipping_costs)

# Replace negative shipping costs with missing values
df.loc[df["shipping_cost"] < 0, "shipping_cost"] = np.nan

# Verify
print("Negative shipping costs after cleaning:",
      (df["shipping_cost"] < 0).sum())

print("Missing shipping costs after cleaning:",
      df["shipping_cost"].isna().sum())

Negative shipping costs before cleaning: 2
Negative shipping costs after cleaning: 0
Missing shipping costs after cleaning: 2

In [33]:
# Check the overall sales calculation discrepancy
print("Recorded sales total:", round(df["sales_amount"].sum(), 2))
print("Expected sales total:", round(df["expected_sales"].sum(), 2))

print("\nSales difference statistics:")
print(df["sales_difference"].describe())

print("\nSample of 10 orders:")
print(
    df[
        ["quantity", "unit_price", "discount_pct",
         "expected_sales", "sales_amount", "sales_difference"]
    ].sample(10, random_state=42).round(2)
)

Recorded sales total: 264269804.54
Expected sales total: 202684235.15

Sales difference statistics:
count    4.200000e+03
mean     1.466323e+04
std      3.002206e+05
min     -2.643429e+05
25%     -3.730640e+02
50%      4.350736e+02
75%      4.274538e+03
max      1.726722e+07
Name: sales_difference, dtype: float64

Sample of 10 orders:
      quantity  unit_price  discount_pct  expected_sales  sales_amount  \
1771       5.0     2324.58          0.20         9298.32       8032.20
2237       5.0      720.42          0.21         2845.66       3357.38
1755       1.0      461.28          0.06          433.60        357.77
3404       4.0     1444.05          0.31         3985.58       6939.46
300        6.0      184.04          0.32          750.88       1193.08
1867       9.0    27363.22          0.29       174850.98     296392.00
4115       2.0    11208.34          0.21        17709.18      28031.47
353       10.0     6308.82          0.36        40376.45      65319.25
3381       8.0     1226.84          0.23         7557.33      11994.58
2504       7.0       79.95          0.03          542.86        404.31

      sales_difference
1771          -1266.12
2237            511.72
1755            -75.83
3404           2953.88
300             442.20
1867         121541.02
4115          10322.29
353           24942.80
3381           4437.25
2504           -138.55

In [34]:
# Remove temporary investigation columns
df = df.drop(
    columns=["expected_sales", "sales_difference"],
    errors="ignore"
)

print("Temporary columns removed.")
print("\nCurrent dataset shape:", df.shape)
print("\nCurrent columns:")
print(df.columns.tolist())

Temporary columns removed.

Current dataset shape: (4200, 21)

Current columns:
['order_id', 'order_date', 'customer_id', 'customer_name', 'age', 'gender', 'region', 'city', 'product_category', 'product_name', 'quantity', 'unit_price', 'discount_pct', 'sales_amount', 'profit', 'shipping_cost', 'payment_method', 'customer_satisfaction', 'return_flag', 'order_status', 'days_to_ship']

In [35]:
# Inspect all column data types
print("Current data types:")
print(df.dtypes)

print("\nMissing values by column:")
print(df.isna().sum())

Current data types:
order_id                            str
order_date               datetime64[ns]
customer_id                         str
customer_name                       str
age                             float64
gender                              str
region                              str
city                                str
product_category                    str
product_name                        str
quantity                        float64
unit_price                      float64
discount_pct                    float64
sales_amount                    float64
profit                          float64
shipping_cost                   float64
payment_method                      str
customer_satisfaction           float64
return_flag                        bool
order_status                        str
days_to_ship                    float64
dtype: object

Missing values by column:
order_id                   0
order_date                 0
customer_id                0
customer_name              0
age                        0
gender                     0
region                     0
city                       0
product_category           0
product_name               0
quantity                   0
unit_price                 0
discount_pct               0
sales_amount               0
profit                     0
shipping_cost              2
payment_method             0
customer_satisfaction    346
return_flag                0
order_status               0
days_to_ship             110
dtype: int64

In [36]:
# Convert whole-number columns to appropriate integer types
df["age"] = df["age"].astype("int64")
df["quantity"] = df["quantity"].astype("int64")

# Use nullable integer because shipping times contain missing values
df["days_to_ship"] = df["days_to_ship"].astype("Int64")

# Verify
print("Updated data types:")
print(df[["age", "quantity", "days_to_ship"]].dtypes)

print("\nMissing shipping times:",
      df["days_to_ship"].isna().sum())

Updated data types:
age             int64
quantity        int64
days_to_ship    Int64
dtype: object

Missing shipping times: 110

In [37]:
print("========== FINAL DATA QUALITY REPORT ==========")

print("\n1. Dataset shape:")
print(df.shape)

print("\n2. Completely empty rows:")
print(df.isna().all(axis=1).sum())

print("\n3. Duplicate rows:")
print(df.duplicated().sum())

print("\n4. Missing values by column:")
print(df.isna().sum())

print("\n5. Invalid ages:")
print(((df["age"] < 18) | (df["age"] > 100)).sum())

print("\n6. Invalid quantities:")
print((df["quantity"] <= 0).sum())

print("\n7. Invalid discounts:")
print(((df["discount_pct"] < 0) | (df["discount_pct"] > 1)).sum())

print("\n8. Invalid shipping times:")
print(
    ((df["days_to_ship"] < 1) | (df["days_to_ship"] > 30))
    .sum()
)

print("\n9. Negative shipping costs:")
print((df["shipping_cost"] < 0).sum())

print("\n10. Order statuses:")
print(df["order_status"].value_counts())

========== FINAL DATA QUALITY REPORT ==========

1. Dataset shape:
(4200, 21)

2. Completely empty rows:
0

3. Duplicate rows:
0

4. Missing values by column:
order_id                   0
order_date                 0
customer_id                0
customer_name              0
age                        0
gender                     0
region                     0
city                       0
product_category           0
product_name               0
quantity                   0
unit_price                 0
discount_pct               0
sales_amount               0
profit                     0
shipping_cost              2
payment_method             0
customer_satisfaction    346
return_flag                0
order_status               0
days_to_ship             110
dtype: int64

5. Invalid ages:
0

6. Invalid quantities:
0

7. Invalid discounts:
0

8. Invalid shipping times:
0

9. Negative shipping costs:
0

10. Order statuses:
order_status
Delivered    2731
Returned      612
Cancelled     346
Shipped       327
Pending       184
Name: count, dtype: int64

In [38]:
from pathlib import Path

# Define output path
output_path = Path("../data/cleaned_dataset.csv")

# Reset the index so the exported file has clean row numbering
df = df.reset_index(drop=True)

# Export the cleaned dataset
df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")
print("File path:", output_path.resolve())
print("Rows exported:", len(df))
print("Columns exported:", len(df.columns))

Cleaned dataset saved successfully!
File path: C:\Users\jhaam\OneDrive\Desktop\SWYNEX-Data-Cleaning-Preparation\data\cleaned_dataset.csv
Rows exported: 4200
Columns exported: 21

In [39]:
# Load the exported cleaned dataset
cleaned_df = pd.read_csv("../data/cleaned_dataset.csv")

# Verify the exported file
print("Exported dataset shape:", cleaned_df.shape)
print("Duplicate rows:", cleaned_df.duplicated().sum())
print("Completely empty rows:", cleaned_df.isna().all(axis=1).sum())

print("\nExported columns match original cleaned DataFrame:",
      list(cleaned_df.columns) == list(df.columns))

print("\nMissing values in exported dataset:")
print(cleaned_df.isna().sum())

print("\nFirst five rows:")
display(cleaned_df.head())

Exported dataset shape: (4200, 21)
Duplicate rows: 0
Completely empty rows: 0

Exported columns match original cleaned DataFrame: True

Missing values in exported dataset:
order_id                   0
order_date                 0
customer_id                0
customer_name              0
age                        0
gender                     0
region                     0
city                       0
product_category           0
product_name               0
quantity                   0
unit_price                 0
discount_pct               0
sales_amount               0
profit                     0
shipping_cost              2
payment_method             0
customer_satisfaction    346
return_flag                0
order_status               0
days_to_ship             110
dtype: int64

First five rows:

,order_id,order_date,customer_id,customer_name,age,gender,region,city,product_category,product_name,...,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship
0,ORD-03903,2024-08-15,CUST32603,Aarav Mehta,39,Other,Central,Raipur,Groceries,Sugar,...,346.32,0.21,4043.14,289.18,56.04,Debit Card,NaN,True,Returned,7.0
1,ORD-02198,2022-08-16,CUST07881,Sanjay Verma,28,Male,West,Mumbai,Beauty,Sunscreen,...,858.66,0.08,9147.31,5355.56,64.49,Debit Card,5.0,False,Delivered,2.0
2,ORD-01348,2021-08-29,CUST49296,Pooja Sharma,41,Other,West,Surat,Furniture,Sofa,...,25941.32,0.14,110156.97,36956.51,67.65,Debit Card,4.0,False,Delivered,5.0
3,ORD-02076,2022-07-05,CUST05587,Priya Reddy,29,Other,West,Ahmedabad,Furniture,Bed Frame,...,22071.92,0.17,262066.11,66644.99,54.47,EMI,3.0,False,Delivered,4.0
4,ORD-00287,2020-05-07,CUST58035,Ritu Sharma,35,Male,Central,Nagpur,Groceries,Cooking Oil,...,320.06,0.31,323.95,31.38,48.81,Net Banking,4.0,False,Pending,4.0